// <auto-generated />
using System;
using FitnessTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Migrations
{
    [DbContext(typeof(FitnessTrackerContext))]
    [Migration("20251206231117_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracker.Models.BodyMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ArmSize")
                        .HasColumnType("float");

                    b.Property<double>("ChestSize")
                        .HasColumnType("float");

                    b.Property<double>("HipSize")
                        .HasColumnType("float");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ThighSize")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WaistSize")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BodyMeasurements");
                });

            modelBuilder.Entity("FitnessTracker.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseCategoryId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Exercises targeting the pectoral muscles",
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Exercises targeting the back muscles including lats, traps, and rhomboids",
                            Name = "Back"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Exercises targeting quadriceps, hamstrings, glutes, and calves",
                            Name = "Legs"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Exercises targeting the deltoid muscles",
                            Name = "Shoulders"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Exercises targeting biceps and triceps",
                            Name = "Arms"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Exercises targeting abdominals and obliques",
                            Name = "Core"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Cardiovascular endurance exercises",
                            Name = "Cardio"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseCategoryId");

                    b.ToTable("ExerciseTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseCategoryId = 1,
                            Name = "Barbell Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            ExerciseCategoryId = 1,
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = 3,
                            ExerciseCategoryId = 1,
                            Name = "Decline Bench Press"
                        },
                        new
                        {
                            Id = 4,
                            ExerciseCategoryId = 1,
                            Name = "Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = 5,
                            ExerciseCategoryId = 1,
                            Name = "Dumbbell Flys"
                        },
                        new
                        {
                            Id = 6,
                            ExerciseCategoryId = 1,
                            Name = "Cable Crossover"
                        },
                        new
                        {
                            Id = 7,
                            ExerciseCategoryId = 1,
                            Name = "Push-Ups"
                        },
                        new
                        {
                            Id = 8,
                            ExerciseCategoryId = 1,
                            Name = "Chest Dips"
                        },
                        new
                        {
                            Id = 9,
                            ExerciseCategoryId = 1,
                            Name = "Machine Chest Press"
                        },
                        new
                        {
                            Id = 10,
                            ExerciseCategoryId = 1,
                            Name = "Pec Deck Machine"
                        },
                        new
                        {
                            Id = 11,
                            ExerciseCategoryId = 2,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 12,
                            ExerciseCategoryId = 2,
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 13,
                            ExerciseCategoryId = 2,
                            Name = "Dumbbell Row"
                        },
                        new
                        {
                            Id = 14,
                            ExerciseCategoryId = 2,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 15,
                            ExerciseCategoryId = 2,
                            Name = "Pull-Ups"
                        },
                        new
                        {
                            Id = 16,
                            ExerciseCategoryId = 2,
                            Name = "Chin-Ups"
                        },
                        new
                        {
                            Id = 17,
                            ExerciseCategoryId = 2,
                            Name = "Seated Cable Row"
                        },
                        new
                        {
                            Id = 18,
                            ExerciseCategoryId = 2,
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = 19,
                            ExerciseCategoryId = 2,
                            Name = "Face Pulls"
                        },
                        new
                        {
                            Id = 20,
                            ExerciseCategoryId = 2,
                            Name = "Hyperextensions"
                        },
                        new
                        {
                            Id = 21,
                            ExerciseCategoryId = 3,
                            Name = "Barbell Squat"
                        },
                        new
                        {
                            Id = 22,
                            ExerciseCategoryId = 3,
                            Name = "Front Squat"
                        },
                        new
                        {
                            Id = 23,
                            ExerciseCategoryId = 3,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 24,
                            ExerciseCategoryId = 3,
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = 25,
                            ExerciseCategoryId = 3,
                            Name = "Leg Curl"
                        },
                        new
                        {
                            Id = 26,
                            ExerciseCategoryId = 3,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = 27,
                            ExerciseCategoryId = 3,
                            Name = "Walking Lunges"
                        },
                        new
                        {
                            Id = 28,
                            ExerciseCategoryId = 3,
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = 29,
                            ExerciseCategoryId = 3,
                            Name = "Calf Raises"
                        },
                        new
                        {
                            Id = 30,
                            ExerciseCategoryId = 3,
                            Name = "Goblet Squat"
                        },
                        new
                        {
                            Id = 31,
                            ExerciseCategoryId = 3,
                            Name = "Hip Thrust"
                        },
                        new
                        {
                            Id = 32,
                            ExerciseCategoryId = 3,
                            Name = "Hack Squat"
                        },
                        new
                        {
                            Id = 33,
                            ExerciseCategoryId = 4,
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 34,
                            ExerciseCategoryId = 4,
                            Name = "Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = 35,
                            ExerciseCategoryId = 4,
                            Name = "Arnold Press"
                        },
                        new
                        {
                            Id = 36,
                            ExerciseCategoryId = 4,
                            Name = "Lateral Raises"
                        },
                        new
                        {
                            Id = 37,
                            ExerciseCategoryId = 4,
                            Name = "Front Raises"
                        },
                        new
                        {
                            Id = 38,
                            ExerciseCategoryId = 4,
                            Name = "Reverse Flys"
                        },
                        new
                        {
                            Id = 39,
                            ExerciseCategoryId = 4,
                            Name = "Upright Rows"
                        },
                        new
                        {
                            Id = 40,
                            ExerciseCategoryId = 4,
                            Name = "Shrugs"
                        },
                        new
                        {
                            Id = 41,
                            ExerciseCategoryId = 4,
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = 42,
                            ExerciseCategoryId = 5,
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = 43,
                            ExerciseCategoryId = 5,
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = 44,
                            ExerciseCategoryId = 5,
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = 45,
                            ExerciseCategoryId = 5,
                            Name = "Preacher Curl"
                        },
                        new
                        {
                            Id = 46,
                            ExerciseCategoryId = 5,
                            Name = "Concentration Curl"
                        },
                        new
                        {
                            Id = 47,
                            ExerciseCategoryId = 5,
                            Name = "Cable Curl"
                        },
                        new
                        {
                            Id = 48,
                            ExerciseCategoryId = 5,
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 49,
                            ExerciseCategoryId = 5,
                            Name = "Skull Crushers"
                        },
                        new
                        {
                            Id = 50,
                            ExerciseCategoryId = 5,
                            Name = "Overhead Tricep Extension"
                        },
                        new
                        {
                            Id = 51,
                            ExerciseCategoryId = 5,
                            Name = "Tricep Dips"
                        },
                        new
                        {
                            Id = 52,
                            ExerciseCategoryId = 5,
                            Name = "Close-Grip Bench Press"
                        },
                        new
                        {
                            Id = 53,
                            ExerciseCategoryId = 5,
                            Name = "Diamond Push-Ups"
                        },
                        new
                        {
                            Id = 54,
                            ExerciseCategoryId = 6,
                            Name = "Crunches"
                        },
                        new
                        {
                            Id = 55,
                            ExerciseCategoryId = 6,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 56,
                            ExerciseCategoryId = 6,
                            Name = "Russian Twists"
                        },
                        new
                        {
                            Id = 57,
                            ExerciseCategoryId = 6,
                            Name = "Leg Raises"
                        },
                        new
                        {
                            Id = 58,
                            ExerciseCategoryId = 6,
                            Name = "Mountain Climbers"
                        },
                        new
                        {
                            Id = 59,
                            ExerciseCategoryId = 6,
                            Name = "Bicycle Crunches"
                        },
                        new
                        {
                            Id = 60,
                            ExerciseCategoryId = 6,
                            Name = "Dead Bug"
                        },
                        new
                        {
                            Id = 61,
                            ExerciseCategoryId = 6,
                            Name = "Ab Rollout"
                        },
                        new
                        {
                            Id = 62,
                            ExerciseCategoryId = 6,
                            Name = "Cable Woodchop"
                        },
                        new
                        {
                            Id = 63,
                            ExerciseCategoryId = 6,
                            Name = "Hanging Knee Raises"
                        },
                        new
                        {
                            Id = 64,
                            ExerciseCategoryId = 7,
                            Name = "Treadmill Running"
                        },
                        new
                        {
                            Id = 65,
                            ExerciseCategoryId = 7,
                            Name = "Stationary Bike"
                        },
                        new
                        {
                            Id = 66,
                            ExerciseCategoryId = 7,
                            Name = "Elliptical"
                        },
                        new
                        {
                            Id = 67,
                            ExerciseCategoryId = 7,
                            Name = "Rowing Machine"
                        },
                        new
                        {
                            Id = 68,
                            ExerciseCategoryId = 7,
                            Name = "Stair Climber"
                        },
                        new
                        {
                            Id = 69,
                            ExerciseCategoryId = 7,
                            Name = "Jump Rope"
                        },
                        new
                        {
                            Id = 70,
                            ExerciseCategoryId = 7,
                            Name = "Burpees"
                        },
                        new
                        {
                            Id = 71,
                            ExerciseCategoryId = 7,
                            Name = "Box Jumps"
                        },
                        new
                        {
                            Id = 72,
                            ExerciseCategoryId = 7,
                            Name = "Kettlebell Swings"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesPerServing")
                        .HasColumnType("float");

                    b.Property<double>("CarbohydratesPerServing")
                        .HasColumnType("float");

                    b.Property<double>("FatsPerServing")
                        .HasColumnType("float");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProteinPerServing")
                        .HasColumnType("float");

                    b.Property<double>("ServingSize")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPerServing = 165.0,
                            CarbohydratesPerServing = 0.0,
                            FatsPerServing = 3.6000000000000001,
                            FoodName = "Chicken Breast",
                            ProteinPerServing = 31.0,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPerServing = 208.0,
                            CarbohydratesPerServing = 0.0,
                            FatsPerServing = 13.0,
                            FoodName = "Salmon",
                            ProteinPerServing = 20.0,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPerServing = 176.0,
                            CarbohydratesPerServing = 0.0,
                            FatsPerServing = 10.0,
                            FoodName = "Ground Beef (90% lean)",
                            ProteinPerServing = 20.0,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPerServing = 78.0,
                            CarbohydratesPerServing = 0.59999999999999998,
                            FatsPerServing = 5.0,
                            FoodName = "Eggs",
                            ProteinPerServing = 6.0,
                            ServingSize = 50.0
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPerServing = 116.0,
                            CarbohydratesPerServing = 0.0,
                            FatsPerServing = 1.0,
                            FoodName = "Tuna (canned)",
                            ProteinPerServing = 26.0,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPerServing = 135.0,
                            CarbohydratesPerServing = 0.0,
                            FatsPerServing = 1.0,
                            FoodName = "Turkey Breast",
                            ProteinPerServing = 30.0,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPerServing = 100.0,
                            CarbohydratesPerServing = 6.0,
                            FatsPerServing = 0.69999999999999996,
                            FoodName = "Greek Yogurt",
                            ProteinPerServing = 17.0,
                            ServingSize = 150.0
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPerServing = 122.0,
                            CarbohydratesPerServing = 12.0,
                            FatsPerServing = 5.0,
                            FoodName = "Milk (2%)",
                            ProteinPerServing = 8.0,
                            ServingSize = 240.0
                        },
                        new
                        {
                            Id = 9,
                            CaloriesPerServing = 98.0,
                            CarbohydratesPerServing = 3.3999999999999999,
                            FatsPerServing = 4.2999999999999998,
                            FoodName = "Cottage Cheese",
                            ProteinPerServing = 11.0,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 10,
                            CaloriesPerServing = 113.0,
                            CarbohydratesPerServing = 0.40000000000000002,
                            FatsPerServing = 9.0,
                            FoodName = "Cheddar Cheese",
                            ProteinPerServing = 7.0,
                            ServingSize = 28.0
                        },
                        new
                        {
                            Id = 11,
                            CaloriesPerServing = 165.0,
                            CarbohydratesPerServing = 35.0,
                            FatsPerServing = 1.5,
                            FoodName = "Brown Rice (cooked)",
                            ProteinPerServing = 3.5,
                            ServingSize = 150.0
                        },
                        new
                        {
                            Id = 12,
                            CaloriesPerServing = 195.0,
                            CarbohydratesPerServing = 45.0,
                            FatsPerServing = 0.40000000000000002,
                            FoodName = "White Rice (cooked)",
                            ProteinPerServing = 4.0,
                            ServingSize = 150.0
                        },
                        new
                        {
                            Id = 13,
                            CaloriesPerServing = 158.0,
                            CarbohydratesPerServing = 27.0,
                            FatsPerServing = 3.0,
                            FoodName = "Oatmeal (cooked)",
                            ProteinPerServing = 6.0,
                            ServingSize = 175.0
                        },
                        new
                        {
                            Id = 14,
                            CaloriesPerServing = 81.0,
                            CarbohydratesPerServing = 14.0,
                            FatsPerServing = 1.0,
                            FoodName = "Whole Wheat Bread",
                            ProteinPerServing = 4.0,
                            ServingSize = 30.0
                        },
                        new
                        {
                            Id = 15,
                            CaloriesPerServing = 220.0,
                            CarbohydratesPerServing = 43.0,
                            FatsPerServing = 1.3,
                            FoodName = "Pasta (cooked)",
                            ProteinPerServing = 8.0,
                            ServingSize = 150.0
                        },
                        new
                        {
                            Id = 16,
                            CaloriesPerServing = 129.0,
                            CarbohydratesPerServing = 30.0,
                            FatsPerServing = 0.10000000000000001,
                            FoodName = "Sweet Potato",
                            ProteinPerServing = 2.0,
                            ServingSize = 150.0
                        },
                        new
                        {
                            Id = 17,
                            CaloriesPerServing = 180.0,
                            CarbohydratesPerServing = 30.0,
                            FatsPerServing = 2.5,
                            FoodName = "Quinoa (cooked)",
                            ProteinPerServing = 6.0,
                            ServingSize = 150.0
                        },
                        new
                        {
                            Id = 18,
                            CaloriesPerServing = 34.0,
                            CarbohydratesPerServing = 7.0,
                            FatsPerServing = 0.40000000000000002,
                            FoodName = "Broccoli",
                            ProteinPerServing = 2.7999999999999998,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 19,
                            CaloriesPerServing = 23.0,
                            CarbohydratesPerServing = 3.6000000000000001,
                            FatsPerServing = 0.40000000000000002,
                            FoodName = "Spinach",
                            ProteinPerServing = 2.8999999999999999,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 20,
                            CaloriesPerServing = 31.0,
                            CarbohydratesPerServing = 7.0,
                            FatsPerServing = 0.10000000000000001,
                            FoodName = "Green Beans",
                            ProteinPerServing = 1.8,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 21,
                            CaloriesPerServing = 41.0,
                            CarbohydratesPerServing = 10.0,
                            FatsPerServing = 0.20000000000000001,
                            FoodName = "Carrots",
                            ProteinPerServing = 0.90000000000000002,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 22,
                            CaloriesPerServing = 31.0,
                            CarbohydratesPerServing = 6.0,
                            FatsPerServing = 0.29999999999999999,
                            FoodName = "Bell Pepper",
                            ProteinPerServing = 1.0,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 23,
                            CaloriesPerServing = 105.0,
                            CarbohydratesPerServing = 27.0,
                            FatsPerServing = 0.40000000000000002,
                            FoodName = "Banana",
                            ProteinPerServing = 1.3,
                            ServingSize = 120.0
                        },
                        new
                        {
                            Id = 24,
                            CaloriesPerServing = 78.0,
                            CarbohydratesPerServing = 21.0,
                            FatsPerServing = 0.20000000000000001,
                            FoodName = "Apple",
                            ProteinPerServing = 0.40000000000000002,
                            ServingSize = 150.0
                        },
                        new
                        {
                            Id = 25,
                            CaloriesPerServing = 62.0,
                            CarbohydratesPerServing = 15.0,
                            FatsPerServing = 0.20000000000000001,
                            FoodName = "Orange",
                            ProteinPerServing = 1.2,
                            ServingSize = 130.0
                        },
                        new
                        {
                            Id = 26,
                            CaloriesPerServing = 57.0,
                            CarbohydratesPerServing = 14.0,
                            FatsPerServing = 0.29999999999999999,
                            FoodName = "Blueberries",
                            ProteinPerServing = 0.69999999999999996,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 27,
                            CaloriesPerServing = 32.0,
                            CarbohydratesPerServing = 7.7000000000000002,
                            FatsPerServing = 0.29999999999999999,
                            FoodName = "Strawberries",
                            ProteinPerServing = 0.69999999999999996,
                            ServingSize = 100.0
                        },
                        new
                        {
                            Id = 28,
                            CaloriesPerServing = 164.0,
                            CarbohydratesPerServing = 6.0,
                            FatsPerServing = 14.0,
                            FoodName = "Almonds",
                            ProteinPerServing = 6.0,
                            ServingSize = 28.0
                        },
                        new
                        {
                            Id = 29,
                            CaloriesPerServing = 188.0,
                            CarbohydratesPerServing = 6.0,
                            FatsPerServing = 16.0,
                            FoodName = "Peanut Butter",
                            ProteinPerServing = 8.0,
                            ServingSize = 32.0
                        },
                        new
                        {
                            Id = 30,
                            CaloriesPerServing = 185.0,
                            CarbohydratesPerServing = 4.0,
                            FatsPerServing = 18.0,
                            FoodName = "Walnuts",
                            ProteinPerServing = 4.2999999999999998,
                            ServingSize = 28.0
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double>("ServingsConsumed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("FitnessTracker.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MealDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FitnessTracker.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("FitnessTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("CalorieTarget")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<int>("HeightFeet")
                        .HasColumnType("int");

                    b.Property<int>("HeightInches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessTracker.Models.WeightEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeightEntries");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("FitnessTracker.Models.BodyMeasurement", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.Exercise", b =>
                {
                    b.HasOne("FitnessTracker.Models.ExerciseCategory", "ExerciseCategory")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseCategory");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseTemplate", b =>
                {
                    b.HasOne("FitnessTracker.Models.ExerciseCategory", "ExerciseCategory")
                        .WithMany("ExerciseTemplates")
                        .HasForeignKey("ExerciseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExerciseCategory");
                });

            modelBuilder.Entity("FitnessTracker.Models.FoodItem", b =>
                {
                    b.HasOne("FitnessTracker.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Models.Meal", "Meal")
                        .WithMany("FoodItems")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FitnessTracker.Models.Meal", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.Set", b =>
                {
                    b.HasOne("FitnessTracker.Models.Exercise", "Exercise")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FitnessTracker.Models.WeightEntry", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithMany("WeightEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutSession", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.Exercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseCategory", b =>
                {
                    b.Navigation("ExerciseTemplates");

                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnessTracker.Models.Meal", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("FitnessTracker.Models.User", b =>
                {
                    b.Navigation("BodyMeasurements");

                    b.Navigation("Meals");

                    b.Navigation("WeightEntries");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("FitnessTracker.Models.WorkoutSession", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
